services:
  mysql:
    image: 'mysql:8.3.0'
    container_name: 'simplified-finance-database'
    environment:
      - MYSQL_DATABASE=simplified-finance-db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=simplified_finance_user
    ports:
      - '3301:3306'
networks:
  simplified-finance-network:
    driver: bridge
    name: simplified-finance-network

